export { default as NavBar } from './NavBar.jsx'
export { default as LatestCollection } from './LatestCollection.jsx'
export { default as Hero } from './Hero.jsx'
export { default as OurPolicy } from './OurPolicy.jsx'
export { default as BestSeller } from './BestSeller.jsx'
export { default as NewsLetterBox } from './NewsLetterBox.jsx'
export { default as Footer } from './Footer.jsx'