export { default as NavBar } from './NavBar.jsx'
export { default as LatestCollection } from './LatestCollection.jsx'
export { default as Hero } from './Hero.jsx'
export { default as OurPolicy } from './OurPolicy.jsx'
export { default as BestSeller } from './BestSeller.jsx'
export { default as NewsLetterBox } from './NewsLetterBox.jsx'
export { default as Footer } from './Footer.jsx'
export { default as ProductItem } from './ProductItem.jsx'
export { default as Title } from './Title.jsx'
export { default as SearchBar} from './SearchBar.jsx'
export { default as RelatedProducts } from './RelatedProducts.jsx'